name: Build and Push Docker Image

on:
  push:
    branches:
      - master
      - 'feature/**'
  pull_request:
    types:
      - closed
    branches:
      - master
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Docker Tag
        id: docker_tag
        run: |
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            echo "TAG=latest" >> $GITHUB_OUTPUT
            echo "tag=latest" >> $GITHUB_ENV
          else
            SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
            echo "TAG=$(date +%Y%m%d%H%M%S)-${SHORT_SHA}" >> $GITHUB_OUTPUT
            echo "tag=$(date +%Y%m%d%H%M%S)-${SHORT_SHA}" >> $GITHUB_ENV
          fi

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot-demo:${{ env.tag }} .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot-demo:${{ env.tag }}
jobs:
  log-event:
    runs-on: ubuntu-latest
    steps:
      - name: Log GitHub Event
        run: echo "${{ toJson(github.event) }}"