name: Reusable Container Builder

on:
  workflow_call:
    inputs:
      image-name:
        description: 'Docker image name'
        required: true
        type: string
      java-version:
        description: 'Java version'
        default: '17'
        type: string
    secrets:
      dockerhub-user:
        required: true
      dockerhub-token:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockerhub-user }}
          password: ${{ secrets.dockerhub-token }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ inputs.image-name }}:latest