name: CI/CD Pipeline

on:
  push:
    branches: [main, master, feature/**]
  pull_request:
    branches: [main, master]

jobs:
  build-container:
    uses: ./.github/workflows/docker-build.yml
    with:
      image-name: 'satishkandekar/spring-boot'
      java-version: '8'
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  code-scan:
    needs: build-container
    uses: ./.github/workflows/sonarcloud.yml
    with:
      project-key: 'satishkandekar_spring-boot-hello-world'
      organization: 'satishkandekar'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}